export const GET_PERSONS_REQUEST = "GET_PERSONS_REQUEST";
export const GET_PERSONS_SUCCESS = "GET_PERSONS_SUCCESS";
export const GET_PERSONS_FAILURE = "GET_PERSONS_FAILURE";

export const GET_PERSON_BY_ID = "GET_PERSON_BY_ID";
export const GET_PERSON_BY_ID_REQUEST = "GET_PERSON_BY_ID_REQUEST";

export const CREATE_PERSON_REQUEST = "CREATE_PERSON_REQUEST";
export const CREATE_PERSON_SUCCESS = "CREATE_PERSON_SUCCESS";
export const CREATE_PERSON_FAILURE = "CREATE_PERSON_FAILURE";

export const PUT_PERSON_REQUEST = "PUT_PERSON_REQUEST";
export const PUT_PERSON_SUCCESS = "PUT_PERSON_SUCCESS";
export const PUT_PERSON_FAILURE = "PUT_PERSON_FAILURE";

export const DELETE_PERSON_REQUEST = "DELETE_PERSON_REQUEST";
export const DELETE_PERSON_SUCCESS = "DELETE_PERSON_SUCCESS";
export const DELETE_PERSON_FAILURE = "DELETE_PERSON_FAILURE";

export const GET_REGIONES_REQUEST = "GET_REGIONES_REQUEST";
export const GET_REGIONES_SUCCESS = "GET_REGIONES_SUCCESS";
export const GET_REGIONES_FAILURE = "GET_REGIONES_FAILURE";