export const GET_ALL_PERSONA = 'GET_ALL_PERSONA';
export const GET_PERSONA_BY_ID = 'GET_PERSONA_BY_ID';
export const CREATE_PERSONA = 'CREATE_PERSONA';
export const UPDATE_PERSONA = 'UPDATE_PERSONA';
export const DELETE_PERSONA_BY_ID = 'DELETE_PERSONA';

export const SAVE_ALL_PERSONA = 'SAVE_ALL_PERSONA';
